package addon

import (
	"embed"

	"github.com/rsfreitas/protoc-gen-mikros-extensions/pkg/settings"
	"github.com/rsfreitas/protoc-gen-mikros-extensions/pkg/template"
)

// Addon is an interface that a supported plugin addon must implement.
type Addon interface {
	// Name sets the addon name.
	Name() string

	// Templates must return all template files that the plugin handle.
	Templates() embed.FS

	// Kind returns the type of templates generated by the addon.
	Kind() template.Kind

	// GetTemplateImports should return a slice of all required imports for a
	// specific template.
	GetTemplateImports(name template.Name, ctx interface{}, cfg *settings.Settings) []*Import

	// GetContext should return a structure that will be available to used or
	// accessed inside templates.
	GetContext() interface{}

	// Validator is the template package validator system that the plugin
	// must also implement.
	template.Validator
}

type Import struct {
	Alias string
	Name  string
}
