// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v5.27.3
// source: proto/domain_improve.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DomainImprove struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NewApi *bool `protobuf:"varint,1,opt,name=new_api,json=newApi" json:"new_api,omitempty"`
}

func (x *DomainImprove) Reset() {
	*x = DomainImprove{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_domain_improve_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DomainImprove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainImprove) ProtoMessage() {}

func (x *DomainImprove) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domain_improve_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainImprove.ProtoReflect.Descriptor instead.
func (*DomainImprove) Descriptor() ([]byte, []int) {
	return file_proto_domain_improve_proto_rawDescGZIP(), []int{0}
}

func (x *DomainImprove) GetNewApi() bool {
	if x != nil && x.NewApi != nil {
		return *x.NewApi
	}
	return false
}

var file_proto_domain_improve_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*DomainImprove)(nil),
		Field:         99000,
		Name:          "mikros_addon.domain_improve.improve",
		Tag:           "bytes,99000,opt,name=improve",
		Filename:      "proto/domain_improve.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional mikros_addon.domain_improve.DomainImprove improve = 99000;
	E_Improve = &file_proto_domain_improve_proto_extTypes[0]
)

var File_proto_domain_improve_proto protoreflect.FileDescriptor

var file_proto_domain_improve_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x5f, 0x69,
	0x6d, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1b, 0x6d, 0x69,
	0x6b, 0x72, 0x6f, 0x73, 0x5f, 0x61, 0x64, 0x64, 0x6f, 0x6e, 0x2e, 0x64, 0x6f, 0x6d, 0x61, 0x69,
	0x6e, 0x5f, 0x69, 0x6d, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x28, 0x0a, 0x0d, 0x44,
	0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x49, 0x6d, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x12, 0x17, 0x0a, 0x07,
	0x6e, 0x65, 0x77, 0x5f, 0x61, 0x70, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x6e,
	0x65, 0x77, 0x41, 0x70, 0x69, 0x3a, 0x67, 0x0a, 0x07, 0x69, 0x6d, 0x70, 0x72, 0x6f, 0x76, 0x65,
	0x12, 0x1f, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x18, 0xb8, 0x85, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x6d, 0x69, 0x6b, 0x72,
	0x6f, 0x73, 0x5f, 0x61, 0x64, 0x64, 0x6f, 0x6e, 0x2e, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x5f,
	0x69, 0x6d, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x2e, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x49, 0x6d,
	0x70, 0x72, 0x6f, 0x76, 0x65, 0x52, 0x07, 0x69, 0x6d, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x42, 0x5f,
	0x5a, 0x5d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x69, 0x6b,
	0x72, 0x6f, 0x73, 0x2d, 0x64, 0x65, 0x76, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67,
	0x65, 0x6e, 0x2d, 0x6d, 0x69, 0x6b, 0x72, 0x6f, 0x73, 0x2d, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73,
	0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2f, 0x61, 0x64,
	0x64, 0x6f, 0x6e, 0x73, 0x2f, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x5f, 0x69, 0x6d, 0x70, 0x72,
	0x6f, 0x76, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f,
}

var (
	file_proto_domain_improve_proto_rawDescOnce sync.Once
	file_proto_domain_improve_proto_rawDescData = file_proto_domain_improve_proto_rawDesc
)

func file_proto_domain_improve_proto_rawDescGZIP() []byte {
	file_proto_domain_improve_proto_rawDescOnce.Do(func() {
		file_proto_domain_improve_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_domain_improve_proto_rawDescData)
	})
	return file_proto_domain_improve_proto_rawDescData
}

var file_proto_domain_improve_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_domain_improve_proto_goTypes = []interface{}{
	(*DomainImprove)(nil),               // 0: mikros_addon.domain_improve.DomainImprove
	(*descriptorpb.MessageOptions)(nil), // 1: google.protobuf.MessageOptions
}
var file_proto_domain_improve_proto_depIdxs = []int32{
	1, // 0: mikros_addon.domain_improve.improve:extendee -> google.protobuf.MessageOptions
	0, // 1: mikros_addon.domain_improve.improve:type_name -> mikros_addon.domain_improve.DomainImprove
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_domain_improve_proto_init() }
func file_proto_domain_improve_proto_init() {
	if File_proto_domain_improve_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_domain_improve_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DomainImprove); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_domain_improve_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_proto_domain_improve_proto_goTypes,
		DependencyIndexes: file_proto_domain_improve_proto_depIdxs,
		MessageInfos:      file_proto_domain_improve_proto_msgTypes,
		ExtensionInfos:    file_proto_domain_improve_proto_extTypes,
	}.Build()
	File_proto_domain_improve_proto = out.File
	file_proto_domain_improve_proto_rawDesc = nil
	file_proto_domain_improve_proto_goTypes = nil
	file_proto_domain_improve_proto_depIdxs = nil
}
